steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/summary-web-service:$COMMIT_SHA'
      - '-t'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/summary-web-service:latest'
      - '-f'
      - 'web-service/Dockerfile'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/summary-web-service:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/summary-web-service:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'summary-web-service'
      - '--image'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/summary-web-service:$COMMIT_SHA'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/summary-web-service:$COMMIT_SHA'
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/summary-web-service:latest'

timeout: '600s'
