steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/sales-ai-automation-v2/sales-ai-automation-v2/slack-app:latest'
      - '-f'
      - 'src/slack_app/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-east1-docker.pkg.dev/sales-ai-automation-v2/sales-ai-automation-v2/slack-app:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'slack-app'
      - '--image=asia-east1-docker.pkg.dev/sales-ai-automation-v2/sales-ai-automation-v2/slack-app:latest'
      - '--region=asia-east1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=SLACK_PROGRESS_TOKEN=3d4ebd6a1cfe8ac77a60e8a69cc4a52a57ad482e940e52d4eb2c17c6c45801d3'

images:
  - 'asia-east1-docker.pkg.dev/sales-ai-automation-v2/sales-ai-automation-v2/slack-app:latest'

timeout: 1200s