/* eslint-disable */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversationsIndexRouteImport } from './routes/conversations/index'
import { Route as ReportsWeeklyRouteImport } from './routes/reports/weekly'
import { Route as ConversationsIdRouteImport } from './routes/conversations/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIndexRoute = ConversationsIndexRouteImport.update({
  id: '/conversations/',
  path: '/conversations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsWeeklyRoute = ReportsWeeklyRouteImport.update({
  id: '/reports/weekly',
  path: '/reports/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIdRoute = ConversationsIdRouteImport.update({
  id: '/conversations/$id',
  path: '/conversations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/reports/weekly': typeof ReportsWeeklyRoute
  '/conversations': typeof ConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/reports/weekly': typeof ReportsWeeklyRoute
  '/conversations': typeof ConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/reports/weekly': typeof ReportsWeeklyRoute
  '/conversations/': typeof ConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conversations/$id' | '/reports/weekly' | '/conversations'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conversations/$id' | '/reports/weekly' | '/conversations'
  id:
    | '__root__'
    | '/'
    | '/conversations/$id'
    | '/reports/weekly'
    | '/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversationsIdRoute: typeof ConversationsIdRoute
  ReportsWeeklyRoute: typeof ReportsWeeklyRoute
  ConversationsIndexRoute: typeof ConversationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/': {
      id: '/conversations/'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/weekly': {
      id: '/reports/weekly'
      path: '/reports/weekly'
      fullPath: '/reports/weekly'
      preLoaderRoute: typeof ReportsWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/$id': {
      id: '/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof ConversationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversationsIdRoute: ConversationsIdRoute,
  ReportsWeeklyRoute: ReportsWeeklyRoute,
  ConversationsIndexRoute: ConversationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
