/* eslint-disable */

// This file is auto-generated by TanStack Router

// Import Route Modules
import { Route as rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as ConversationsIndexRoute } from './routes/conversations/index';
import { Route as ConversationsIdRoute } from './routes/conversations/$id';
import { Route as ReportsWeeklyRoute } from './routes/reports/weekly';

// Create Route Tree
export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ConversationsIndexRoute,
  ConversationsIdRoute,
  ReportsWeeklyRoute,
]);
