/* eslint-disable */

// @ts-nocheck

// This file is auto-generated by TanStack Router

import { createFileRoute, createRootRoute } from '@tanstack/react-router';

// Import Route Modules
import { Route as rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as ConversationsIndexRoute } from './routes/conversations/index';
import { Route as ConversationsIdRoute } from './routes/conversations/$id';
import { Route as ReportsWeeklyRoute } from './routes/reports/weekly';

// Create Route Tree
const routeTree = rootRoute.addChildren([
  IndexRoute,
  ConversationsIndexRoute,
  ConversationsIdRoute,
  ReportsWeeklyRoute,
]);

export { routeTree };
