"""
Coach Evaluation Skill.

Wraps Agent 5 (CoachAgent) as a Skill.
Evaluates if coaching alerts should be triggered based on analysis results.
"""

from dataclasses import dataclass, field
from typing import Any, Optional

from core.skills import (
    Skill,
    SkillCategory,
    SkillContext,
    SkillMetadata,
    SkillResult,
)


@dataclass
class CoachInput:
    """Input for Coach Evaluation Skill."""
    case_id: str
    rep_id: str
    rep_name: str
    store_name: str
    context_insights: dict[str, Any]
    buyer_insights: dict[str, Any]
    seller_insights: dict[str, Any]


@dataclass
class CoachAlert:
    """Alert generated by the coach."""
    alert_type: str  # close_now | missed_dm | excellent | low_progress
    message: str
    suggestion: str
    progress_score: int
    urgency: str
    decision_maker: str


@dataclass
class CoachOutput:
    """Output from Coach Evaluation Skill."""
    should_alert: bool = False
    alert: Optional[CoachAlert] = None
    slack_blocks: list[dict[str, Any]] = field(default_factory=list)
    raw_data: dict[str, Any] = field(default_factory=dict)


class CoachEvaluationSkill(Skill[CoachInput, CoachOutput]):
    """
    Skill that evaluates if coaching alerts should be triggered.

    Wraps the existing CoachAgent (Agent 5) from the MEDDIC system.
    Uses rule-based evaluation to determine if real-time alerts
    should be sent to sales reps or managers.
    """

    # Alert templates matching the original CoachAgent
    ALERT_TEMPLATES = {
        "close_now": {
            "emoji": "🔥",
            "title": "立即成交機會",
            "message": "客戶急迫度高且決策者到場，這是成交的絕佳時機！",
            "suggestion": "建議 24 小時內發送報價，把握成交機會。",
        },
        "missed_dm": {
            "emoji": "⚠️",
            "title": "錯失關鍵人物",
            "message": "客戶需求急迫，但本次 Demo 僅員工接待。",
            "suggestion": "建議盡快約老闆或主管進行第二次 Demo。",
        },
        "excellent": {
            "emoji": "🏆",
            "title": "優異表現",
            "message": "這次 Demo 推進力極高，做得非常好！",
            "suggestion": "繼續保持，這個客戶很有機會成交。",
        },
        "low_progress": {
            "emoji": "📉",
            "title": "需要關注",
            "message": "這次 Demo 推進力偏低，可能需要調整策略。",
            "suggestion": "建議回顧對話，找出客戶的真正顧慮並跟進。",
        },
    }

    @property
    def metadata(self) -> SkillMetadata:
        return SkillMetadata(
            id="meddic.coach-evaluation",
            name="Coach Evaluation",
            version="1.0.0",
            description="Evaluates if coaching alerts should be triggered",
            category=SkillCategory.ANALYSIS,
            tags=["meddic", "sales", "coaching", "alerts"],
            requires_llm=False,  # Rule-based evaluation
            estimated_duration_seconds=1.0,
        )

    def execute(
        self,
        input_data: CoachInput,
        context: SkillContext,
    ) -> SkillResult[CoachOutput]:
        """Execute coach evaluation using rule-based logic."""
        try:
            # Extract key metrics from insights
            progress_score = input_data.seller_insights.get("progress_score", 0)
            strategy = input_data.seller_insights.get("recommended_strategy", "")
            urgency = input_data.context_insights.get("urgency_level", "中")
            decision_maker = input_data.context_insights.get("decision_maker", "")

            # Evaluate rules
            alert_type = self._evaluate_rules(
                progress_score=progress_score,
                strategy=strategy,
                urgency=urgency,
                decision_maker=decision_maker,
            )

            if alert_type is None:
                return SkillResult.ok(
                    data=CoachOutput(
                        should_alert=False,
                        raw_data={
                            "progress_score": progress_score,
                            "evaluated": True,
                            "reason": "No alert conditions met",
                        },
                    ),
                    metadata={"evaluated_rules": 4},
                )

            # Build alert
            template = self.ALERT_TEMPLATES[alert_type]
            alert = CoachAlert(
                alert_type=alert_type,
                message=template["message"],
                suggestion=template["suggestion"],
                progress_score=progress_score,
                urgency=urgency,
                decision_maker=decision_maker,
            )

            # Build Slack blocks
            slack_blocks = self._build_slack_blocks(
                alert=alert,
                store_name=input_data.store_name,
            )

            return SkillResult.ok(
                data=CoachOutput(
                    should_alert=True,
                    alert=alert,
                    slack_blocks=slack_blocks,
                    raw_data={
                        "progress_score": progress_score,
                        "alert_type": alert_type,
                        "store_name": input_data.store_name,
                    },
                ),
                metadata={
                    "alert_type": alert_type,
                    "progress_score": progress_score,
                },
            )

        except Exception as e:
            return SkillResult.fail(error=str(e))

    def _evaluate_rules(
        self,
        progress_score: int,
        strategy: str,
        urgency: str,
        decision_maker: str,
    ) -> Optional[str]:
        """
        Evaluate coaching rules to determine alert type.

        Returns alert_type string or None if no alert needed.
        """
        # Rule 1: Close Now opportunity
        if progress_score >= 80 and "CloseNow" in strategy:
            return "close_now"

        # Rule 2: Missed decision maker
        if self._is_high_urgency(urgency) and self._is_staff_only(decision_maker):
            return "missed_dm"

        # Rule 3: Excellent performance
        if progress_score >= 90:
            return "excellent"

        # Rule 4: Low progress (disabled to reduce notification noise)
        # if progress_score < 40:
        #     return "low_progress"

        return None

    def _is_high_urgency(self, urgency: str) -> bool:
        """Check if urgency level is high."""
        return any(k in urgency.lower() for k in ["高", "high", "urgent", "緊急"])

    def _is_staff_only(self, decision_maker: str) -> bool:
        """Check if only staff attended (no decision maker)."""
        dm_lower = decision_maker.lower()
        staff_keywords = ["員工", "staff", "店員", "服務員"]
        boss_keywords = ["老闆", "owner", "主管", "manager", "經理"]

        has_staff = any(k in dm_lower for k in staff_keywords)
        has_boss = any(k in dm_lower for k in boss_keywords)

        return has_staff and not has_boss

    def _build_slack_blocks(
        self,
        alert: CoachAlert,
        store_name: str,
    ) -> list[dict[str, Any]]:
        """Build Slack Block Kit message for the alert."""
        template = self.ALERT_TEMPLATES.get(alert.alert_type, {})
        emoji = template.get("emoji", "💡")
        title = template.get("title", "銷售教練提醒")

        return [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"{emoji} 【{title}】",
                    "emoji": True,
                },
            },
            {
                "type": "section",
                "fields": [
                    {"type": "mrkdwn", "text": f"*客戶：*\n{store_name}"},
                    {"type": "mrkdwn", "text": f"*推進分數：*\n{alert.progress_score}"},
                ],
            },
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": alert.message},
            },
            {"type": "divider"},
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"💡 *建議：*\n{alert.suggestion}"},
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "有疑慮請直接在此 thread 回覆，我會查看對話記錄回應你。",
                    }
                ],
            },
        ]

    def validate_input(self, input_data: CoachInput) -> Optional[str]:
        """Validate input data."""
        if not input_data.case_id:
            return "case_id is required"
        if not input_data.rep_id:
            return "rep_id is required"
        if not input_data.seller_insights:
            return "seller_insights is required for coach evaluation"
        return None
