steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-east1-docker.pkg.dev/sales-ai-automation-v2/sales-ai-automation-v2/slack-app:latest', '.']
  dir: 'src/slack_app'

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-east1-docker.pkg.dev/sales-ai-automation-v2/sales-ai-automation-v2/slack-app:latest']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run',
    'deploy',
    'slack-app',
    '--image', 'asia-east1-docker.pkg.dev/sales-ai-automation-v2/sales-ai-automation-v2/slack-app:latest',
    '--region', 'asia-east1',
    '--min-instances', '1',
    '--cpu', '1',
    '--memory', '512Mi',
    '--concurrency', '5',
    '--allow-unauthenticated',
    '--set-env-vars=PYTHONPATH=/app,GCP_PROJECT_ID=sales-ai-automation-v2,SLACK_AUDIO_BUCKET=sales-ai-audio-bucket,TRANSCRIPTION_TASK_QUEUE=transcription-queue,TRANSCRIPTION_TASK_HANDLER_URL=https://transcription-service-497329205771.asia-east1.run.app/transcribe,TRANSCRIPTION_TASK_SERVICE_ACCOUNT=497329205771-compute@developer.gserviceaccount.com,SUMMARY_BASE_URL=https://summary-web-service-497329205771.asia-east1.run.app,SHORT_URL_BASE=https://summary-web-service-497329205771.asia-east1.run.app/s,SMS_SERVICE_URL=https://sms-service-497329205771.asia-east1.run.app',
    '--set-secrets=SLACK_BOT_TOKEN=slack-bot-token:latest,SLACK_SIGNING_SECRET=slack-signing-secret:latest,SMS_INTERNAL_TOKEN=sms-internal-token:latest'
  ]

images:
- 'asia-east1-docker.pkg.dev/sales-ai-automation-v2/sales-ai-automation-v2/slack-app:latest'

