/* eslint-disable */

// This file is auto-generated by TanStack Router

// Import Route Modules
import { Route as rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as SettingsRoute } from './routes/settings';
import { Route as AgentsRoute } from './routes/agents';

// Create Route Tree
export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SettingsRoute,
  AgentsRoute,
]);
