/* eslint-disable */

// @ts-nocheck

// This file is auto-generated by TanStack Router

import { createFileRoute, createRootRoute } from '@tanstack/react-router';

// Import Route Modules
import { Route as rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as SettingsRoute } from './routes/settings';
import { Route as AgentsRoute } from './routes/agents';

// Create Route Tree
const routeTree = rootRoute.addChildren([
  IndexRoute,
  SettingsRoute,
  AgentsRoute,
]);

export { routeTree };
