/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康檢查 */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出對話記錄 */
        get: operations["list_conversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得對話詳情 */
        get: operations["get_conversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得對話分析結果 */
        get: operations["get_conversation_analysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得儀表板統計 */
        get: operations["get_dashboard_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/weekly-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得週報摘要 */
        get: operations["get_weekly_report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得分析趨勢 */
        get: operations["get_trends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/rep/{rep_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得業務員統計 */
        get: operations["get_rep_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Conversation: {
            /** @description 對話 ID */
            id: string;
            /** @description 關聯的潛客 ID */
            leadId?: string | null;
            /** @description 業務員名稱 */
            salesRepName?: string | null;
            /**
             * @description 狀態
             * @enum {string}
             */
            status: "pending" | "transcribing" | "analyzing" | "completed" | "failed";
            /**
             * @description 對話類型
             * @enum {string|null}
             */
            conversationType?: "discovery" | "demo" | "negotiation" | "follow_up" | "closing" | null;
            /**
             * Format: date-time
             * @description 建立時間
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 完成時間
             */
            completedAt?: string | null;
        };
        ConversationListResponse: {
            items: components["schemas"]["Conversation"][];
            total: number;
            limit: number;
            offset: number;
        };
        TranscriptSegment: {
            speaker?: string | null;
            text: string;
            /** @description 開始時間 (秒) */
            start?: number | null;
            /** @description 結束時間 (秒) */
            end?: number | null;
        };
        Transcript: {
            segments: components["schemas"]["TranscriptSegment"][];
            fullText?: string | null;
            /** @default zh-TW */
            language: string;
            durationSeconds?: number | null;
        };
        MEDDICData: {
            /** @description 量化指標 */
            metrics?: string | null;
            /** @description 經濟決策者 */
            economicBuyer?: string | null;
            /** @description 決策標準 */
            decisionCriteria?: string | null;
            /** @description 決策流程 */
            decisionProcess?: string | null;
            /** @description 痛點 */
            identifyPain?: string | null;
            /** @description 支持者 */
            champion?: string | null;
        };
        BuyerData: {
            /** @description 已識別需求 */
            identifiedNeeds?: string[];
            /** @description 疑慮 */
            hesitations?: string[];
            /** @description 痛點 */
            painPoints?: string[];
            /** @description 信任分數 */
            trustScore?: number | null;
            meddic?: components["schemas"]["MEDDICData"];
        };
        CoachingInsight: {
            /** @enum {string} */
            category: "strength" | "improvement" | "action";
            content: string;
            /** @enum {string|null} */
            priority?: "high" | "medium" | "low" | null;
        };
        SellerCoaching: {
            progressScore?: number | null;
            recommendedStrategy?: string | null;
            insights?: components["schemas"]["CoachingInsight"][];
            nextSteps?: string[];
        };
        AnalysisResult: {
            contextData?: {
                [key: string]: unknown;
            } | null;
            buyerData?: components["schemas"]["BuyerData"];
            sellerCoaching?: components["schemas"]["SellerCoaching"];
            meddicScore?: number | null;
            summary?: string | null;
            /** @description 客戶摘要 (可發送給客戶) */
            customerSummary?: string | null;
            /** Format: date-time */
            analyzedAt?: string | null;
        };
        ConversationDetail: components["schemas"]["Conversation"] & {
            transcript?: components["schemas"]["Transcript"];
            analysis?: components["schemas"]["AnalysisResult"];
            audioFileUri?: string | null;
            audioDurationSeconds?: number | null;
        };
        PerformerStats: {
            id: string;
            name: string;
            conversationCount: number;
            avgMeddicScore: number;
            /** @enum {string|null} */
            trend?: "up" | "down" | "stable" | null;
        };
        DashboardStats: {
            totalConversations: number;
            completedToday: number;
            pendingAnalysis: number;
            avgMeddicScore: number;
            conversionRate: number;
            topPerformers: components["schemas"]["PerformerStats"][];
            /** @enum {string|null} */
            recentTrend?: "improving" | "declining" | "stable" | null;
            /** Format: date-time */
            lastUpdated: string;
        };
        WeeklyReportSummary: {
            /** Format: date-time */
            periodStart: string;
            /** Format: date-time */
            periodEnd: string;
            totalConversations: number;
            totalAnalyzed: number;
            avgMeddicScore: number;
            byRep: components["schemas"]["PerformerStats"][];
            insights: string[];
            /** Format: date-time */
            generatedAt: string;
        };
        TrendData: {
            /** Format: date */
            date: string;
            conversationCount: number;
            avgMeddicScore: number;
        };
        AnalyticsTrends: {
            /** @enum {string} */
            period: "7d" | "30d" | "90d";
            data: components["schemas"]["TrendData"][];
            /** @enum {string} */
            overallTrend: "improving" | "declining" | "stable";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example healthy */
                        status?: string;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
        };
    };
    list_conversations: {
        parameters: {
            query?: {
                /** @description 篩選狀態 */
                status?: string;
                /** @description 篩選業務員 */
                sales_rep?: string;
                /** @description 開始日期 */
                start_date?: string;
                /** @description 結束日期 */
                end_date?: string;
                /** @description 數量限制 */
                limit?: number;
                /** @description 分頁偏移 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
        };
    };
    get_conversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_conversation_analysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
        };
    };
    get_dashboard_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    get_weekly_report: {
        parameters: {
            query?: {
                /** @description 週開始日期 */
                week_start?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyReportSummary"];
                };
            };
        };
    };
    get_trends: {
        parameters: {
            query?: {
                /** @description 期間 */
                period?: "7d" | "30d" | "90d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsTrends"];
                };
            };
        };
    };
    get_rep_stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rep_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformerStats"];
                };
            };
        };
    };
}
